FROM node:18-alpine as builder
WORKDIR /app
COPY package.json package.json
RUN npm install --legacy-peer-deps || npm install
COPY . .
ARG VITE_API_URL=http://192.168.50.39
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]1~FROM node:18-alpine as builder
WORKDIR /app
COPY package.json package.json
RUN npm install --legacy-peer-deps || npm install
COPY . .
ARG VITE_API_URL=http://192.168.50.39
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
