services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ticketing_db
      POSTGRES_USER: ticketing_user
      POSTGRES_PASSWORD: Ticket2026!!
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://ticketing_user:Ticket2026!!@db:5432/ticketing_db
      JWT_ACCESS_SECRET: Ticket2026!!_access_jwt_secret_super_sicuro
      JWT_REFRESH_SECRET: Ticket2026!!_refresh_jwt_secret_diverso
      APP_URL: http://192.168.50.39
      NODE_ENV: production
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/usr/src/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://192.168.50.39
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
